trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'cemp-api'
  containerRegistry: 'containerregistrycemp.azurecr.io'
  dockerfilePath: 'docker/Dockerfile'
  imageTag: '$(Build.BuildId)'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- script: |
    dotnet restore
    dotnet build --configuration Release
  displayName: 'Restore and Build'

- script: |
    docker build -t $(containerRegistry)/$(imageRepository):$(imageTag) -f $(dockerfilePath) .
  displayName: 'Build Docker Image'

- script: |
    echo "Push to ACR will be configured in the next session."
  displayName: 'Placeholder'