apiVersion: v1
kind: Secret

metadata:
  name: cemp-secret

type: Opaque

stringData:
  DB_USERNAME: "sa"
  DB_PASSWORD: "Password@123"
  API_KEY: "CEMP-2026-SECRET"

apiVersion: v1
kind: Secret

metadata:
  name: cemp-secret

type: Opaque

stringData:
  DB_USERNAME: "sa"
  DB_PASSWORD: "Password@123"
  API_KEY: "CEMP-2026-SECRET"
