{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cemp-api-ingress
  labels:
    {{- include "cemp-chart.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - host: cemp.local
    http:
      paths:
            - path: /
        pathType: Prefix
        backend:
          service:
            name: cemp-api-service
            port:
              number: 80
{{- end }}