apiVersion: v1
kind: Service
metadata:
  name: cemp-api-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: cemp-chart
    app.kubernetes.io/instance: cemp