replicaCount: 1

image:
  repository: containerregistrycemp.azurecr.io/cemp-api
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
    - name: acr-secret

serviceAccount:
  create: false

service:
  type: NodePort
  port: 80
  nodePort: 30080

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false